#!/usr/bin/env python
"""Bridge: Phylo's best evolved genome -> a SIA-compatible target_agent.py seed.

Phylo SEARCHES the harness space (population + crossover/mutation); SIA RUNS the winner.
This takes the highest-fitness genome from the Phylo run (web/lineage.json) and writes:
  1. phylo/exports/sia_target_agent.py  — a complete SIA target agent with the evolved
     system_prompt / meta_instructions / output_format baked in (SIA contract: argparse
     --dataset_dir/--working_dir, writes predictions.jsonl + agent_execution.json).
  2. phylo/profiles/evolved-target.json — a SIA target-agent profile whose agent_reference
     points at #1, so SIA seeds its next run from the evolved harness.

Run SIA from the evolved seed:
  sia run --task_dir ./tasks/text-to-sql --max_gen 5 --run_id 9 \
          --target-agent-profile ./phylo/profiles/evolved-target.json

Usage:  python tools/export_to_sia.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]            # E:\sia\phylo
LINEAGE = ROOT / "web" / "lineage.json"
OUT_AGENT = ROOT / "exports" / "sia_target_agent.py"
OUT_PROFILE = ROOT / "profiles" / "evolved-target.json"

AGENT_TEMPLATE = '''#!/usr/bin/env python
"""SIA target agent — harness EVOLVED by Phylo.

Source genome: {gid}  (execution accuracy {fit:.3f}, operator={op}).
Generated by phylo/tools/export_to_sia.py. Conforms to the SIA target-agent contract:
launched as `python target_agent.py --dataset_dir <ro> --working_dir <rw>`, calls only
the task model, writes predictions.jsonl + agent_execution.json into --working_dir.
"""
from __future__ import annotations
import argparse, json, os, time
from pathlib import Path
import anthropic

MODEL = os.environ.get("SIA_TASK_MODEL", "claude-haiku-4-5-20251001")
MAX_TOKENS = 1024
MAX_RETRIES = 4

# ── evolved harness sections (discovered by Phylo's population search) ──────────
SYSTEM_PROMPT = {system_prompt}
META_INSTRUCTIONS = {meta_instructions}
OUTPUT_FORMAT = {output_format}


def call_model(system: str, user: str) -> str:
    client = anthropic.Anthropic()
    last = None
    for i in range(MAX_RETRIES):
        try:
            r = client.messages.create(model=MODEL, max_tokens=MAX_TOKENS, system=system,
                                       messages=[{{"role": "user", "content": user}}])
            return "".join(b.text for b in r.content if getattr(b, "type", None) == "text")
        except Exception as e:  # noqa: BLE001
            last = e; time.sleep(2 ** i)
    raise RuntimeError(f"model call failed: {{last}}")


def extract_sql(raw: str) -> str:
    t = (raw or "").strip()
    if "```" in t:
        blocks = [b for i, b in enumerate(t.split("```")) if i % 2 == 1]
        if blocks:
            t = max(blocks, key=len).strip()
            if t[:3].lower() == "sql":
                t = t[3:].strip()
    return t.strip()


def build_user(schema: str, question: str) -> str:
    return f"{{META_INSTRUCTIONS}}\\n\\nDatabase schema:\\n{{schema}}\\n\\nQuestion: {{question}}\\n\\n{{OUTPUT_FORMAT}}"


def read_jsonl(p: Path):
    return [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset_dir", required=True)
    ap.add_argument("--working_dir", required=True)
    args = ap.parse_args()
    dataset, work = Path(args.dataset_dir), Path(args.working_dir)
    work.mkdir(parents=True, exist_ok=True)

    questions = read_jsonl(dataset / "test_questions.jsonl")
    schemas = json.loads((dataset / "schemas.json").read_text(encoding="utf-8"))
    print(f"Evolved harness answering {{len(questions)}} questions. Model={{MODEL}}")

    predictions, log = [], []
    for i, q in enumerate(questions):
        schema = schemas.get(q["db_id"], "")
        try:
            raw = call_model(SYSTEM_PROMPT, build_user(schema, q["question"]))
            sql = extract_sql(raw)
        except Exception as e:  # noqa: BLE001
            raw, sql = f"[error] {{e}}", ""
        predictions.append({{"id": q["id"], "predicted_sql": sql}})
        log.append({{"id": q["id"], "db_id": q["db_id"], "question": q["question"], "raw_output": raw[:1000], "predicted_sql": sql}})
        print(f"[{{i+1}}/{{len(questions)}}] {{q['id']}}: {{sql[:80]}}")

    with open(work / "predictions.jsonl", "w", encoding="utf-8") as f:
        for p in predictions:
            f.write(json.dumps(p, ensure_ascii=False) + "\\n")
    with open(work / "agent_execution.json", "w", encoding="utf-8") as f:
        json.dump(log, f, indent=2, ensure_ascii=False)
    print(f"Wrote {{len(predictions)}} predictions to {{work / 'predictions.jsonl'}}")


if __name__ == "__main__":
    main()
'''


def main():
    if not LINEAGE.exists():
        raise SystemExit(f"{LINEAGE} not found — run a Phylo evolution first.")
    lin = json.loads(LINEAGE.read_text(encoding="utf-8"))
    best = lin.get("best")
    if not best:
        raise SystemExit("no best genome in lineage.json")

    code = AGENT_TEMPLATE.format(
        gid=best["id"], fit=best.get("fitness") or 0.0, op=best.get("operator", "?"),
        system_prompt=json.dumps(best.get("system_prompt", "")),
        meta_instructions=json.dumps(best.get("meta_instructions", "")),
        output_format=json.dumps(best.get("output_format", "")),
    )
    OUT_AGENT.parent.mkdir(parents=True, exist_ok=True)
    OUT_AGENT.write_text(code, encoding="utf-8")

    profile = {
        "profile_id": "evolved-target",
        "name": f"Phylo-evolved target ({best['id']}, fitness {round(best.get('fitness') or 0, 3)})",
        "model": "claude-haiku-4-5-20251001",
        "provider_id": "anthropic",
        "agent_reference": {"source": str(OUT_AGENT)},
    }
    OUT_PROFILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_PROFILE.write_text(json.dumps(profile, indent=2), encoding="utf-8")

    print(f"best genome: {best['id']}  fitness={best.get('fitness')}")
    print(f"wrote SIA target agent -> {OUT_AGENT}")
    print(f"wrote SIA target profile -> {OUT_PROFILE}")
    print("\nRun SIA from the evolved seed:")
    print(f"  sia run --task_dir ./tasks/text-to-sql --max_gen 5 --run_id 9 \\")
    print(f"          --target-agent-profile {OUT_PROFILE}")


if __name__ == "__main__":
    main()
