#!/usr/bin/env python
"""SIA target agent — harness EVOLVED by Phylo.

Source genome: gen_2:pop_1:agent_2  (execution accuracy 0.675, operator=mutation).
Generated by phylo/tools/export_to_sia.py. Conforms to the SIA target-agent contract:
launched as `python target_agent.py --dataset_dir <ro> --working_dir <rw>`, calls only
the task model, writes predictions.jsonl + agent_execution.json into --working_dir.
"""
from __future__ import annotations
import argparse, json, os, time
from pathlib import Path
import anthropic

MODEL = os.environ.get("SIA_TASK_MODEL", "claude-haiku-4-5-20251001")
MAX_TOKENS = 1024
MAX_RETRIES = 4

# ── evolved harness sections (discovered by Phylo's population search) ──────────
SYSTEM_PROMPT = "You are a text-to-SQL system. Given a SQLite database schema and a question, output one SQLite SELECT query that answers it."
META_INSTRUCTIONS = "Read the schema carefully, then write a single complete SQLite SELECT query that answers the question.\n\nBefore writing SQL, identify which tables are needed and the correct join keys.\n\nFollow these rules:\n- Use exact table and column names from the schema; do not invent fields (e.g., avoid guessed columns like MakeId if the schema shows Id).\n- Join on declared primary/foreign keys or identically named key columns (e.g., Id). Choose INNER JOIN by default; use LEFT JOIN only if the question requires keeping rows with no matches (e.g., \"all X including those with 0\").\n- Use exact string literals and casing as stored in the data (e.g., 'Africa', 'English').\n- For exclusions (\"do not\", \"without\", \"no\"), prefer NOT EXISTS over NOT IN to avoid NULL-related errors.\n- Interpret quantifiers precisely:\n  - \"greater/larger than any in ...\" or \"greater than all in ...\" -> compare to MAX(...) of that set.\n  - \"smaller/less than any in ...\" or \"less than all in ...\" -> compare to MIN(...) of that set.\n  - \"at least one\"/\"there exists\" -> use EXISTS.\n- For questions about a language spoken by the largest percentage in a country, compare that row's Percentage to the per-country MAX(Percentage) with a correlated subquery (e.g., cl.Percentage = (SELECT MAX(Percentage) FROM countrylanguage cl2 WHERE cl2.CountryCode = cl.CountryCode)).\n- Use GROUP BY with all non-aggregated selected columns; put aggregate filters in HAVING.\n- Avoid unnecessary CAST(); use values as stored.\n- Only add DISTINCT or ORDER BY when explicitly requested by the question.\n- Return exactly one complete, executable SQL statement with no commentary or extra text."
OUTPUT_FORMAT = "Output only the SQL query. No markdown, no commentary."


def call_model(system: str, user: str) -> str:
    client = anthropic.Anthropic()
    last = None
    for i in range(MAX_RETRIES):
        try:
            r = client.messages.create(model=MODEL, max_tokens=MAX_TOKENS, system=system,
                                       messages=[{"role": "user", "content": user}])
            return "".join(b.text for b in r.content if getattr(b, "type", None) == "text")
        except Exception as e:  # noqa: BLE001
            last = e; time.sleep(2 ** i)
    raise RuntimeError(f"model call failed: {last}")


def extract_sql(raw: str) -> str:
    t = (raw or "").strip()
    if "```" in t:
        blocks = [b for i, b in enumerate(t.split("```")) if i % 2 == 1]
        if blocks:
            t = max(blocks, key=len).strip()
            if t[:3].lower() == "sql":
                t = t[3:].strip()
    return t.strip()


def build_user(schema: str, question: str) -> str:
    return f"{META_INSTRUCTIONS}\n\nDatabase schema:\n{schema}\n\nQuestion: {question}\n\n{OUTPUT_FORMAT}"


def read_jsonl(p: Path):
    return [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset_dir", required=True)
    ap.add_argument("--working_dir", required=True)
    args = ap.parse_args()
    dataset, work = Path(args.dataset_dir), Path(args.working_dir)
    work.mkdir(parents=True, exist_ok=True)

    questions = read_jsonl(dataset / "test_questions.jsonl")
    schemas = json.loads((dataset / "schemas.json").read_text(encoding="utf-8"))
    print(f"Evolved harness answering {len(questions)} questions. Model={MODEL}")

    predictions, log = [], []
    for i, q in enumerate(questions):
        schema = schemas.get(q["db_id"], "")
        try:
            raw = call_model(SYSTEM_PROMPT, build_user(schema, q["question"]))
            sql = extract_sql(raw)
        except Exception as e:  # noqa: BLE001
            raw, sql = f"[error] {e}", ""
        predictions.append({"id": q["id"], "predicted_sql": sql})
        log.append({"id": q["id"], "db_id": q["db_id"], "question": q["question"], "raw_output": raw[:1000], "predicted_sql": sql})
        print(f"[{i+1}/{len(questions)}] {q['id']}: {sql[:80]}")

    with open(work / "predictions.jsonl", "w", encoding="utf-8") as f:
        for p in predictions:
            f.write(json.dumps(p, ensure_ascii=False) + "\n")
    with open(work / "agent_execution.json", "w", encoding="utf-8") as f:
        json.dump(log, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(predictions)} predictions to {work / 'predictions.jsonl'}")


if __name__ == "__main__":
    main()
